### PR TITLE
Forgot Password

### PR DESCRIPTION
**Pull request by skeswa**
Forgot password along with email-related dependencies and one fix to CSS for event card padding.

### CODE REVIEW

**Comment by skeswa** [comment]
Kinda huge. Take your time.

**Comment by SriRamanujam** [comment]
Comments: 
1) We are leaking information to attackers in routes/member.js. Make all error messages as generic as possible to avoid leaking.
2) Don't put crap in the 404 page.

**Comment by SriRamanujam** [comment]
Further issues:

In the password reset email, you've provided the user a link to "tuacm.temple.edu". However, this is not a valid URL. Either you meant "acm.temple.edu" or "tuacm@temple.edu". Please to change.

**Comment by skeswa** [comment]
Try it again.

**Comment by SriRamanujam** [comment]
Make sure that mailing works with the tuacm@temple.edu

**Pull request merged**
